test commit
cloud-native-toolkit/terraform-gitops-cp-event-streams-instance pull request #1
Opened 2022-02-18 07:32 UTC by JyotiRani

Signed-off-by: Jyoti Rani <jyotirani10@in.ibm.com>

2022-03-17 05:08 UTC, JyotiRani commented
@seansund @triceam please review.

2022-03-30 13:58 UTC, JyotiRani commented
@seansund @triceam  please review this.

2022-04-04 05:21 UTC, JyotiRani commented
Please review and approve.

2022-04-12 16:21 UTC, seansund requested changes
Update handling of the namespace in the helm chart

2022-04-12 16:21 UTC, seansund commented on charts/ibm-es-instance/templates/es-instance.yaml
> +  namespace: {{ .Values.namespace}}
The namespace shouldn't be provided in the values file. It should be retrieved from `{{ .Release.Namespace }}'

2022-04-12 16:21 UTC, seansund commented on charts/ibm-es-instance/values.yaml
> +namespace: openshift-operators
Remove this from values.yaml and pass the namespace in with the release

2022-04-25 04:58 UTC, JyotiRani commented
Completed the review comments https://github.com/cloud-native-toolkit/terraform-gitops-cp-event-streams-instance/issues/4 however unable to test due to common services issue on cluster. Please review the changes and confirm.

2022-04-27 05:17 UTC, seansund approved these changes
lgtm

2022-04-27 06:40 UTC, merged

2022-04-27 06:41 UTC, JyotiRani commented
Merged with main branch